# This action sends a "repository_dispatch" event to the qooxdoo/test.githubactions.incoming repository, 
# in order to trigger a build. 

name: Trigger build in qooxdoo/test.githubactions.incoming
on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: actions/bin/curl@master    
      with: 
        args: >
          -s 
          -u "${{ secrets.WEBHOOK_USER }}:${{ secrets.WEBHOOK_TOKEN }}"
          -H "Accept:application/vnd.github.everest-preview+json"
          -H "Content-Type:application/json"
          -d "{\\\"event_type\\\":\\\"build\\\"}"
          https://api.github.com/repos/qooxdoo/test.githubactions.incoming/dispatches
