# This action sends a "repository_dispatch" event to the qooxdoo/experimental repository, 
# in order to trigger a build. 

name: Trigger build in qooxdoo/experimental
on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1     
      with: 
        args: -X POST -u "${{ secrets.WEBHOOK_USER }}:${{ secrets.WEBHOOK_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/qooxdoo/experimental/dispatches --data "{\u0022event_type\u0022: \u0022build\u0022}"
        

